### ISSUE TITLE
build: add py3.11 support; use Debian 11

### ISSUE THREAD

**Issue by kushagra189** [elixir-cloud-aai/foca#174]
Python 3.7 has been deprecated and hence removed from the `foca` workflow. We need to add the additional support for new stable python 3.11 version.

**Comment by uniqueg** [comment]
Add this point, we may provide support for Python 3.12 as well, at the same time, if it doesn't cause too many problems. I would be okay with dropping support for 3.8.

**Comment by uniqueg** [comment]
Given py3.12 stability issues, I have created a separate issue (#199) for adding py3.12 support, removing py3.8 support and migrating base images to Debian Bookworm (v12).

In this issue, let's focus on:
- [ ] adding support for py3.11
- [ ] using Python images built based on Debian Bullseye (v11) instead of Debian Buster (v10; end of life: [2024-07](https://devguide.python.org/versions/))
