### ISSUE TITLE
Add security package modules with unit tests

### ISSUE THREAD

**Issue by sarthakgupta072** [elixir-cloud-aai/foca#25]
Check if there are differences between the Python modules in the following (sub)packages:

https://github.com/elixir-europe/WES-ELIXIR/tree/dev/wes_elixir/security
https://github.com/elixir-europe/proTES/tree/dev/pro_tes/security
https://github.com/elixir-europe/proWES/tree/dev/pro_wes/security

If there are differences, summarize and discuss differences. If not, add modules to archetype (adjusting import paths).

**Comment by sarthak-sopho** [comment]
https://github.com/elixir-cloud-aai/proTES/tree/dev/pro_tes/security doesn't have `decorators.py` module. Do, we need to include this as a part of archetype?

**Comment by uniqueg** [comment]
Thanks @sarthak-sopho! It's a little complicated. I will need some time to look at this in detail to figure out what the most up-to-date version is

**Comment by uniqueg** [comment]
Okay @sarthak-sopho, I have just worked quite a bit on `cwl-WES`'s version of `security/decorators.py` - which is now the most up-to-date version and so should be the one to use here. See elixir-cloud-aai/cwl-WES#151

**Comment by uniqueg** [comment]
Things to note here:
* check for required parameters to pass through the decorator in order to guarantee generic use; also, set reasonable defaults to allow simple use
* for unit tests relying on service/HTTP calls to identity provider, mock up responses in cases where valid token requirement is essential for the code to proceed

**Comment by uniqueg** [comment]
Closed by #30
