### ISSUE TITLE
Generalization of the errors module

### ISSUE THREAD

**Issue by kushagra189** [elixir-cloud-aai/foca#36]
Generalize the current behavior of the `errors` [module](https://github.com/elixir-cloud-aai/foca/tree/dev/foca/errors) by passing an error model to FOCA's `register_error_handlers()`  function and then pass that model to the different handlers. Also find a way to pass actual error parameters (like the exact error message) to a single handler which will match it to the model. Lastly write unit tests for the same. In this way, :
- only need a single handler
- can define the model in each service according to how it is defined in the specs
- don't require the service developer to overwrite error handlers one by one

**Comment by uniqueg** [comment]
Issue #40 might perhaps serve as an inspiration how to do this

**Comment by stikos** [comment]
I thought about this a bit and wanted to check with you if I'm on the right track, so that I can give it a try. 
We can create an `FOCAError` model class that:

- Inherits from Exception
- Has 2 attributes and 1 class method
- The 1st attribute is an instance of (kind of 'children') classes. The reason for this is that with a simple `switch-case` statement in the constructor we can create the appropriate children class.
- The 2nd attribute is a Response instance
- The class method simply returns the Response attribute
- The set of children classes consists of one class per error (BadRequest, Unauthorized etc), each of which define the Response attribute appropriately

My question regarding the description of the issue above is how can we pass the *exact error message* since `app.add_error_handler()` accepts only the error code and the handler function?
