### ISSUE TITLE
Interpret relative paths from the location of the config file

### ISSUE THREAD

**Issue by sarthakgupta072** [elixir-cloud-aai/foca#78]
FOCA interprets relative paths with reference to the current working directory, but it's not portable. We should change the code such that the relative paths in `config.yaml` are interpreted relative to the location of the `config file`.

**Comment by kushagra189** [comment]
@sarthakgupta072  can you elaborate this a little more? Relative to the `config file` as in the `config.py`???

**Comment by sarthakgupta072** [comment]
Right @kushagra189 .

**Comment by sarthakgupta072** [comment]
@kushagra189 

As far as I remember when we call the `foca()`method to get the app instance, we provide the path of the config file (`config.yaml`) relative to the directory in which we are working in. For example, if you see [here](https://github.com/elixir-cloud-aai/drs-filer/blob/dev/drs_filer/app.py), we are not giving
```
app = foca("config.yaml")
```
but instead giving:
```
app = foca(
        os.path.join(
            os.path.dirname(__file__),
            "config.yaml",
        )
    )
```

but the former type of declaration should work. @uniqueg can confirm if this was the exact issue or not. Sorry, I don't seem to recall that much.

P.S: The issue title and description may be misleading because it tells a different story altogether :|

**Comment by uniqueg** [comment]
Actually, I'm not so sure about this issue.

I think, ideally, users should be able to supply absolute and relative paths.
In reality though, there is probably not much use for absolute paths, because they won't be portable (may be different in each system/container). So when speaking of relative paths, we need to think what relative _to_. I see the following options:

1. Paths are relative to the current working directory of the agent that is executing the code. This would be the traditional definition of relative paths, but it makes it hard for the user to know what to put, and it limits portability / the ability to start the app from anywhere (which options 2 and 3 both provide). So I would rather not do that.
2. Paths are always relative to the directories of the files in which they are defined (e.g., `config.yaml`, `app.py`). This allows a bit greater flexibility in the way that an app using FOCA can be structured (compared to option 3). But I find it a little harder to work with as the user, because the reference may be different for paths provided in different files. Plus if you move the files, you need to adapt the paths.
3. Paths are interpreted relative to a fixed anchor. Conceptually, this is probably the simplest solution _for the user_ and I would probably prefer that **_if_** we could find a good solution for implementing it. Specifically, I would suggest to use the app (not the project) root directory as the anchor. So, e.g., for TRS-Filer, it would be the _inner_ `trs_filer` directory containing, well, both `app.py` and `config.yaml`.

Since all of the paths that app developers need to be provide are either in the main app module (e.g., `app.py`) or the configuration (e.g., `config.yaml`), and in our cases so far these files reside in the same directory, options 2. and 3. are actually identical in appearance. But as @sarthakgupta072's example shows, the current _implementation_ is consistent with option 2. It's arguably much easier to implement, because how do we want to know what the app root directory _is_ unless we make assumptions on where files specifying relative paths are actually located within the app's directory tree. We could specify this as an option in the config file, but (1) this is somewhat inconsistent (we have to implement option 2 for that path and then options 3 for _all other paths_) and also won't work for passing the config file _itself_. So to make this work in this way we'd have to give the user way too many information.

So, I'd say unless we find a solution that does _not_ require so many assumptions/rules, we could implement option 3. Otherwise I think we should just verify that option 2 is consistently implemented for the cases where paths are handled and then close this issue without implementing anything new.

One possibility to explore is to use the app package as an anchor. Perhaps there is a way to get from each module to the root package (e.g., `trs_filer`) and get directories in this way. It still requires each app wanting to make use of FOCA to _be_ a package (i.e., have at least a `setup.py` file), but I think that assumption is valid enough, because the package/module structure is required by Connexion (for pointing to the controllers and the auth handler function) and FOCA (for pointing to the exceptions dictionary).

Let's explore this and then see. Or if you have any other suggestions, let's hear them :)

**Comment by uniqueg** [comment]
> As far as I remember when we call the `foca()`method to get the app instance, we provide the path of the config file (`config.yaml`) relative to the directory in which we are working in. For example, if you see [here](https://github.com/elixir-cloud-aai/drs-filer/blob/dev/drs_filer/app.py), we are not giving
> 
> ```
> app = foca("config.yaml")
> ```
> 
> but instead giving:
> 
> ```
> app = foca(
>         os.path.join(
>             os.path.dirname(__file__),
>             "config.yaml",
>         )
>     )
> ```

@sarthakgupta072 @kushagra189: did one of you actually try (with the latest foca version) what actually happens if you try the first option, i.e., `foca("config.yaml")`? At least in the petstore example it seems to work (but then this is _inside_ the FOCA package so it may be different).

...because if it works, I think we can close the issue :)

**Comment by sarthakgupta072** [comment]
Hey @uniqueg 

I checked in `drs-filer`, the relative parts are getting interpreted now. This code `foca("config.yaml")` also works. We can close this issue 😄  

Though I don't really understand, why was it not working earlier?

**Comment by uniqueg** [comment]
Thanks, closing this then :)
